ecommerce_admin_subCategories:
    resource: "@EcommerceBundle/Resources/config/routing/routingSubCategoriesAdmin.yml"
    prefix:   /admin/subCategories

routingAdmin:
  resource: "@EcommerceBundle/Resources/config/routing/routingAdmin.yml"
  prefix: /admin

routingPanier:
  resource: "@EcommerceBundle/Resources/config/routing/routingPanier.yml"
  prefix: /panier

routingProduits:
  resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
  prefix: /

routingPartenairesAdmin:
  resource: "@EcommerceBundle/Resources/config/routing/routingPartenairesAdmin.yml"
  prefix: /admin/partenaires

routingGarantiesAdmin:
  resource: "@EcommerceBundle/Resources/config/routing/routingGarantiesAdmin.yml"
  prefix: /admin/garanties

routingProduitsAdmin:
  resource: "@EcommerceBundle/Resources/config/routing/routingProduitsAdmin.yml"
  prefix: /admin/produits

routingRayonAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingRayonAdmin.yml"
    prefix:   /admin/rayon

routingMediaAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingMediaAdmin.yml"
    prefix:   /admin/media

routingCategoriesAdmin:
    resource: "@EcommerceBundle/Resources/config/routing/routingCategoriesAdmin.yml"
    prefix:   /admin/categories

routingCommandesAdmin:
  resource: "@EcommerceBundle/Resources/config/routing/routingCommandesAdmin.yml"
  prefix: /admin/commandes

routingCommandes:
  resource: "@EcommerceBundle/Resources/config/routing/routingCommandes.yml"
  prefix: /