adminMedia:
    path:     /
    defaults: { _controller: "EcommerceBundle:MediaAdmin:index" }

adminMedia_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:MediaAdmin:show" }

adminMedia_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:MediaAdmin:new" }

adminMedia_create:
    path:     /create
    defaults: { _controller: "EcommerceBundle:MediaAdmin:create" }
    requirements: { _method: post }

adminMedia_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:MediaAdmin:edit" }

adminMedia_update:
    path:     /{id}/update
    defaults: { _controller: "EcommerceBundle:MediaAdmin:update" }
    requirements: { _method: post|put }

adminMedia_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:MediaAdmin:delete" }
    requirements: { _method: post|delete }
