routingUtilisateursAdmin:
    resource: "@UtilisateursBundle/Resources/config/routing/routingUtilisateursAdmin.yml"
    prefix: /admin/utilisateurs

routingUtilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing/routingUtilisateurs.yml"
    prefix: /

routingContact:
    resource: "@UtilisateursBundle/Resources/config/routing/routingContact.yml"
    prefix: /contact